import 'package:flutter/cupertino.dart';
import 'package:stacked/stacked.dart';
import 'package:stacked_services/stacked_services.dart';
import 'package:yalla_health/app/app.locator.dart';
import 'package:yalla_health/app/app.router.dart';
import 'package:yalla_health/core/constants/app_constants.dart';
import 'package:yalla_health/core/utils/egyptian_phone_formatter.dart';
import 'package:yalla_health/core/validators/form_validators.dart';
import 'package:yalla_health/features/authentication/domain/usecases/register_usecase.dart';
import 'package:yalla_health/features/authentication/ui/views/register_view.form.dart';

class RegisterViewModel extends FormViewModel with $RegisterView {
  final NavigationService _navigationService = locator<NavigationService>();
  final SnackbarService _snackbarService = locator<SnackbarService>();
  final RegisterUseCase _registerUseCase = locator<RegisterUseCase>();

  String? _errorMessage;
  String? get errorMessage => _errorMessage;

  String? _selectedGender;
  String? get selectedGender => _selectedGender;

  // Controllers and focus nodes are auto-generated by @FormView
  // They are available through the $RegisterView mixin

  final List<String> genderOptions = ['male', 'female'];
  
  // Store raw user input separate from formatted display
  String _rawPhoneInput = '';

  @override
  void dispose() {
    disposeForm();
    super.dispose();
  }

  String get formattedPhone => EgyptianPhoneFormatter.format(_rawPhoneInput);
  
  String get cleanPhone => EgyptianPhoneFormatter.clean(_rawPhoneInput);
  
  
  bool get isFormValid {
    return hasValidName && hasValidPhone && hasValidAge && hasValidGender && hasValidEmail;
  }
  
  bool get hasValidName => nameController.text.trim().isNotEmpty;
  bool get hasValidPhone => EgyptianPhoneFormatter.isValid(_rawPhoneInput);
  bool get hasValidAge => ageController.text.isNotEmpty && int.tryParse(ageController.text) != null;
  bool get hasValidGender => _selectedGender != null;
  bool get hasValidEmail => emailController.text.isEmpty || emailController.text.contains('@');
  
  bool get canRegister => isFormValid && !isBusy;

  void onPhoneChanged(String value) {
    _clearError();
    
    // Store only digits from user input
    _rawPhoneInput = EgyptianPhoneFormatter.extractDigits(value);
    
    // Format for display
    final formatted = formattedPhone;
    
    // Update controller with formatted text, avoiding loops
    if (formatted != phoneController.text) {
      phoneController.value = TextEditingValue(
        text: formatted,
        selection: TextSelection.collapsed(offset: formatted.length),
      );
    }
    
    notifyListeners();
  }

  void onNameChanged(String value) {
    _clearError();
    notifyListeners();
  }

  void onEmailChanged(String value) {
    _clearError();
    notifyListeners();
  }

  void onAgeChanged(String value) {
    _clearError();
    notifyListeners();
  }

  void setGender(String? gender) {
    _selectedGender = gender;
    _clearError();
    notifyListeners();
  }

  Future<void> register() async {
    if (!isFormValid) {
      _snackbarService.showSnackbar(
        message: 'Please fill all required fields correctly',
        title: 'Form Incomplete',
        duration: const Duration(seconds: AppConstants.snackbarErrorDuration),
      );
      return;
    }

    setBusy(true);
    _clearError();

    final params = RegisterParams(
      name: nameController.text.trim(),
      phone: cleanPhone,
      gender: _selectedGender!,
      age: int.parse(ageController.text),
      email: emailController.text.trim().isEmpty ? null : emailController.text.trim(),
    );

    final result = await _registerUseCase.call(params);

    result.fold(
      (failure) {
        _errorMessage = failure.message;
        _snackbarService.showSnackbar(
          message: failure.message,
          title: 'Registration Failed',
          duration: const Duration(seconds: AppConstants.snackbarErrorDuration),
        );
        notifyListeners();
      },
      (success) {
        _snackbarService.showSnackbar(
          message: 'OTP sent successfully',
          title: 'Success',
          duration: const Duration(seconds: AppConstants.snackbarSuccessDuration),
        );
        _navigationService.navigateTo(
          Routes.otpView,
          arguments: OtpViewArguments(
            phone: cleanPhone,
            isRegistration: true,
          ),
        );
      },
    );

    setBusy(false);
  }

  void navigateToLogin() {
    _navigationService.replaceWith(Routes.loginView);
  }

  void _clearError() {
    if (_errorMessage != null) {
      _errorMessage = null;
      notifyListeners();
    }
  }

  @override
  void setFormStatus() {
    final nameValidation = FormValidators.validateName(nameController.text);
    final phoneValidation = FormValidators.validateEgyptianPhone(cleanPhone);
    final emailValidation = FormValidators.validateEmail(emailController.text);
    final ageValidation = FormValidators.validateAge(ageController.text);
    final genderValidation = FormValidators.validateGender(_selectedGender);

    final hasErrors = nameValidation != null ||
        phoneValidation != null ||
        emailValidation != null ||
        ageValidation != null ||
        genderValidation != null;

    setValidationMessage(hasErrors ? 'Please fix the errors above' : null);
  }
}